theme: jekyll-theme-leap-day
title: Neill's micro:bit resources
description: challenges, demos, and discussion
lang: en
show_downloads: false

collections:
    activities:
        output: false
        permalink: /activities/:path/
    demos:
        output: false
        permalink: /demos/:path/
    discussions:
        output: true
        permalink: /discussions/:path/
    howtos:
        output: false
        permalink: /howtos/:path/
    kit:
        output: true
        permalink: /kit/:path/
    workshops:
        output: true
        permalink: /workshops/:path/
